# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for twelve-data-mcp-server

# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app
# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
RUN npm ci --ignore-scripts
# Copy source and build
COPY src ./src
RUN npm run build

# Production stage
FROM node:lts-alpine
WORKDIR /app
# Copy built files and package info
COPY --from=builder /app/dist ./dist
COPY package.json package-lock.json ./
# Install production dependencies only
RUN npm ci --omit=dev --ignore-scripts
# Set environment
ENV NODE_ENV=production
# Default entrypoint, configFunction will supply args
ENTRYPOINT ["node", "dist/index.js"]
CMD ["--apikey", ""]
